### ISSUE TITLE
JSONata for the data-mapper piece

### ISSUE THREAD

**Issue by lukaiser** [activepieces/activepieces#1249]
I love the data-mapper piece. But in its current form it is a little limited.
I also love https://jsonata.org/. Basically, the same thing, but way more powerful.
Could it be a solution to just use jsonata for the data-mapper piece?
Just an idea! Thx for the great work!

**Comment by abuaboud** [comment]
This is an inventive idea, and I'm fond of it. The Data Mapper is just a piece like any other, actually, it's quite simple. Here's the code:

https://github.com/activepieces/activepieces/blob/main/packages/pieces/data-mapper/src/lib/actions/advanced-mapping.ts

However, I have a worry that jsonnata seems to demand a learning curve for its usage. We usually try to evade such pieces because they complicate our UX, especially for the no-code and beginner users. Nevertheless, it does appear to be a promising prospect for a private piece that can be shared or installed. What's your viewpoint on this?

**Comment by lukaiser** [comment]
I do understand the concern regarding UX. Mastering it is indeed a learning curve. But the basic operations (what the Data Mapper is already capable of) are as simple as the current Data Mapper. It might therefore "just" be a question of how to frame the help section of the piece. For example, keep the examples as simple as they are now with a hit, that there is way more possible -> Link to the JSONata doc.

I am aware of the other two options. And I am more than happy with any of them. I just wanted to make sure, that not a lot of time for feature requests and development is "wasted" for slowly adding features to the Data Mapper that JSONata is already capable of.
I guess now it is basically a product management decision.
Thanks any way!

**Comment by AbdulTheActivePiecer** [comment]
We really appreciate this @lukaiser ! we might need this as a utility for JSON actually not for the mapper specifically, maybe for selecting JSON properties with conditions and/or concatenate them, it would make sense in that use case, but currently that's a bit out scope, however I have a feeling we could use JSONata one way or another, thanks again for letting us know :D
