### ISSUE TITLE
More install options for self-hosting

### ISSUE THREAD

**Issue by nileshtrivedi** [activepieces/activepieces#1277]
There exist some tools that make it easy to self-host open-source apps.

- [CapRover](caprover.com/) - FOSS
- [Cloudron](https://www.cloudron.io/) - Paid, non-FOSS
- [Sandstorm](https://sandstorm.io/) - FOSS
- [HomeLabOS](https://homelabos.com/)
- [Yunohost](https://yunohost.org/)
- [Coolify](https://coolify.io/)

Personally, I'm interested in CapRover. It should be simple to transform the Docker Compose file into a [captain-definition](https://caprover.com/docs/docker-compose.html) file and make it available as a [one-click app](https://github.com/caprover/one-click-apps) in their catalog.

**Comment by abuaboud** [comment]
You are amazing, I was literally looking for such a list!

Let's keep this issue open and get the templates ready!

**Comment by abuaboud** [comment]
Activepieces can run in single docker image now using sqlite3 and in memory queue, marking this as complete.

**Comment by jdaviescoates** [comment]
> You are amazing, I was literally looking for such a list!

@abuaboud there is a much longer list of such things e.g. here https://forum.cloudron.io/topic/10000/a-list-of-cloudron-like-services-competitors

BTW, whilst Cloudron itself isn't fully FOSS, it is source available, plus all the app packages themselves are FOSS and they also contribute a lot to FOSS upstream. It's also by far the best one IMHO (if you search the Cloudron Forum you'll find loads of happy users who have tried all the others listed and found them lacking - very often just because the packages aren't maintained, but also because none of the other e.g. include a full email server, nor deal with updates and backups are well etc etc).
