### ISSUE TITLE
Create a way of managing persistent connections for the use in triggers and pieces.

### ISSUE THREAD

**Issue by x7airworker** [activepieces/activepieces#1414]
**Is your feature request related to a problem? Please describe.**
I want to implement triggers and pieces for IRC and AMQP, but currently only polling and webhooks are supported.

**Describe the solution you'd like**
There needs to be some kind of manager which handles connections, disconnects unused connections, handles reconnects and has the ability to be used in a trigger and piece.

**Additional context**
Although this is pretty protocol unspecific, here are examples and documentation for IRC and AMQP:
[AMQP (RabbitMQ)](https://www.rabbitmq.com/tutorials/tutorial-one-javascript.html) 
[IRC](https://www.rfc-editor.org/rfc/rfc1459)

**Comment by JanHolger** [comment]
This will be hard to implement in a good way since it would permanently block a sandbox but I definitely see use cases for this aswell. Right now there is a hacky workaround of setting the interval of a polling trigger to 1 minute and keeping it up for a minute but this would still produce some data loss and still block a sandbox infinitely. I also thought about using a sidecar service that users can setup (or purchase for a markup in the cloud) but that would probably kill the ux for pieces using it.

**Comment by abuaboud** [comment]
@JanHolger I think it's a good idea to avoid making things more complicated when it comes to hosting. For example, if we want to scale such service, it will be connected to the main part of it.

I'm closing this ticket now as not planned, feel free to reopen if you are not satisfied with answer.
