### ISSUE TITLE
Question: Remove spaces from the body

### ISSUE THREAD

**Issue by briannezhad** [activepieces/activepieces#1551]
**Describe the bug**
I am trying to pass trigger data into HTTP connector for Jira, but my data come in with space, and Jira label field don't accept space. is there anyway in my `body` request trim the 

**Expected behavior**
Remove Spaces before sending the body data.

**Screenshots**
<img width="1688" alt="Screenshot 2023-06-25 at 12 54 16 PM" src="https://github.com/activepieces/activepieces/assets/10551124/a4f5635d-b575-4857-a486-ceed61a9bfe8">

<img width="655" alt="Screenshot 2023-06-25 at 12 54 24 PM" src="https://github.com/activepieces/activepieces/assets/10551124/f3285bb9-f545-42c8-9c07-d2bf4fb6120f">

<img width="433" alt="Screenshot 2023-06-25 at 12 54 34 PM" src="https://github.com/activepieces/activepieces/assets/10551124/93243280-2fd6-429b-8cf0-8abd886f908a">

**Comment by abuaboud** [comment]
There is multiple way, but I see you are running an old version of activepieces since (${}) is used, It's now changed {{}}.

The only way I can think of for your version is that you add code piece and write the code that remove the spaces.

Please close the ticket, If that does answer your question.

**Comment by briannezhad** [comment]
How do I upgrade it? I am new to Activepieces. I install it thru easypanel.

**Comment by abuaboud** [comment]
I'm not certain about the exact instructions for the easy panel, but I usually update their templates but it takes time until they merge and release, you can ask them how to do it for existing version as I am not familar.

However, I recommend upgrading so that you can directly write JavaScript code. For instance, you could use `{{trigger.body['YOUR_KEY'].replace(" ","")}}` as an example.

If you're working with the current version, you can create a code piece that includes the strings as input. In the code, simply replace empty spaces, and then use them in http piece.

**Comment by briannezhad** [comment]
Wow this is amazing. ok i will find a way to upgrade this. Thank you so much.

**Comment by abuaboud** [comment]
Your welcome, I am closing this issue, If you have another question please reopen it

**Comment by briannezhad** [comment]
It says I am using latest version of HTTP. but I get the error.

<img width="836" alt="Screenshot 2023-06-25 at 2 38 19 PM" src="https://github.com/activepieces/activepieces/assets/10551124/04b05ccf-b792-4d9e-ad2d-ea2700d4ebfe">
<img width="841" alt="Screenshot 2023-06-25 at 2 40 44 PM" src="https://github.com/activepieces/activepieces/assets/10551124/1a90b19d-4969-46ec-8d72-d755483d7015">
