### ISSUE TITLE
Google Sheets Enhancement

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#1568]
**Is your feature request related to a problem? Please describe.**
- Use First Row as Labels in all actions
- Support Clear whole sheets expect first row.

**Comment by zdaar** [comment]
Suggestions : 
Add a range of column to the query, can go from a single column to a range like in any sheets with standard syntax A:Z
Add starting point because many sheets have headers that may be undesirable to parse so you dont need to do housekeeping in post processing
Add a row limit to stop iterating on row retrieval
return data in a tree like
rows
1
A : Debit
B: 23-06-25
C: Uncategorized
2
A: account
B: 23-06-25
C: Bills

or as json

```
{
  "1": {
    "A": "Debit",
    "B": "23-06-25",
    "C": "Uncategorized"
  },
  "2": {
    "A": "account",
    "B": "23-06-25",
    "C": "Bills"
  }
}
```
