### ISSUE TITLE
[BUG]: Empty Facebook Leads Flow

### ISSUE THREAD

**Issue by ilovefreesw** [activepieces/activepieces#1917]
**Describe the bug**
 The Facebook Leads trigger is empty in the self-hosted version by Docker. In the cloud version, there is the option for authentication as well new lead event, but that is missing in the self-hosted version.
**To Reproduce**
1. Create a new flow
2. Choose Facebook Leads as trigger
3. Click on it and nothing shows in the sidebar.

**Expected behavior**
Just like the cloud version, it should display the New Lead trigger with the Authentication option.

**Screenshots**
The Self Hosted Version:

![image](https://github.com/activepieces/activepieces/assets/77317006/36b3e3e6-2a89-4eb0-957f-746320324bd1)

The Cloud version:

![image](https://github.com/activepieces/activepieces/assets/77317006/61038014-6014-4232-a15d-e042700a774d)

**Comment by abuaboud** [comment]
The reason it doesn't appear on self-hosted but on the cloud is due to the way Facebook webhooks work.

Facebook sends all events belonging to users connected to that app in a single webhook, which means we have developed an external service that captures these events. Then, there is logic to identify the user from the payload and trigger that person's flows.

It's because of this technical reason that we couldn't make it possible on self-hosted. We are actively seeking workarounds or, at the very least, a tutorial for self-hosted individuals.

The same applies to Slack Triggers and Square Triggers. We will clarify this on the website soon and will continue to search for a workaround.

I will close it as duplicate in favor of this issue: https://github.com/activepieces/activepieces/issues/765

**Comment by ilovefreesw** [comment]
> I will close it as duplicate in favor of this issue: #765

Sure no problem.
