### ISSUE TITLE
Webhook Trigger is not working.

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#217]
The webhook trigger on local / demo instance is returning:

```json
{
    "code": "INSTANCE_NOT_FOUND"
}
```

**Comment by khaledmashaly** [comment]
I have tested the `webhook` flow and it's working, here are the steps I followed:
1. Create a new collection
2. Create a new flow
3. Update trigger to `webhook`
4. Publish the collection
5. Test `webhook`
Can you please send the steps you used to get the `INSTANCE_NOT_FOUND` error? Please keep in mind that if you don't publish the collection you will get an `INSTANCE_NOT_FOUND`, Is this the expected behaviour?
@abuaboud @AbdulTheActivePiecer
