### ISSUE TITLE
Lead Connector (GoHighLevel)

### ISSUE THREAD

**Issue by Activepieces-Apps** [activepieces/activepieces#2694]
Trigger when new form is submitted.

Trigger when purchase is submitted.

Trigger when certain tags are assigned to a contact. 

Trigger when certain # used in Community.

**Comment by abuaboud** [comment]
https://github.com/activepieces/activepieces/issues/1905

**Comment by ilovefreesw** [comment]
Hey, any plans to support custom fields for Create and Update contact actions?

https://highlevel.stoplight.io/docs/integrations/791462a3367b9-get-custom-fields

Also, the new "Private Integrations" (GHL allows generating private API tokens per subaccount basis to use API without creating marketplace app). So don't have to create the marketplace app in order to work with Lead Connector.
