### ISSUE TITLE
Integrate pull request preview environments

### ISSUE THREAD

**Issue by waveywaves** [activepieces/activepieces#299]
**Is your feature request related to a problem? Please describe.**
I would like to support Activepieces by implementing [Uffizzi](https://github.com/UffizziCloud/uffizzi) preview environments.
Disclaimer: I work on [Uffizzi](https://github.com/UffizziCloud/uffizzi).

Uffizzi is a Open Source full stack previews engine and our platform is available completely free for Activepieces (and all open source projects). This will provide maintainers with preview environments of every PR in the cloud, which enables faster iterations and reduces time to merge. You can see the open source repos which are currently using Uffizzi over [here](https://uffizzi.notion.site/)

Uffizzi is purpose-built for the task of previewing PRs and it integrates with your workflow to deploy preview environments in the background without any manual steps for maintainers or contributors.

We can go ahead and create an Initial PoC for you right away if you think there is value in this proposal.

**Comment by abuaboud** [comment]
Thank you for this nice offer, This would help us a lot specially in reviewing connector by the contributors, Let's create an initial POC and see.

**Comment by abuaboud** [comment]
@waveywavesAfter careful consideration with the team, due to the nature of our product, we typically use personal third-party accounts (such as personal Google and Stripe accounts) during testing. These data are not stored on our servers. Based on this, the best option currently available is to self-host your solution.

However, as we are at capacity at the moment, we will have to revisit the option to self host in the future.
