### ISSUE TITLE
Shopify

### ISSUE THREAD

**Issue by abuaboud** [activepieces/activepieces#3339]
**Actions**
1. Adjust Inventory Level
2. Cancel Order
3. Close Order
4. Create Collect
5. Create Customer
6. Create Draft Order
7. Create Fulfillment Event
8. Create Order
9. Create Product
10. Create Transaction
11. Get Asset
12. Get Customer Orders
13. Get Customer
14. Get Fulfillment
15. Get Fulfillments
16. Get Locations
17. Get Product Variant
18. Get Product
19. Get Products
20. Get Transaction
21. Get Transactions
22. Update Customer
23. Update Order
24. Update Product
25. Upload Product Image

**Triggers**
1. New Abandoned Checkout
2. Updated Product

**Comment by b4s36t4** [comment]
@abuaboud as far as I see there is not event topic available for New Abandoned Checkout, how does this works, can you help me, if possible I'll work on it.

https://shopify.dev/docs/api/admin-rest/2023-10/resources/webhook#event-topics

**Comment by b4s36t4** [comment]
Also for this `Watch Products` watching for `product/updated` topic works?

**Comment by amitray007** [comment]
@b4s36t4 For Operations like creation, updation or even deletion of Products or Variants, these events should be used: `products/(create/update/delete)` specifically.

Just curious, Doesn't this require a public Shopify app to be installed in a Shopify store to get these webhook events and make specified actions? If Yes, Will there be an `activepieces` Shopify app too for supporting this piece which should be installed in order to create Shopify triggers or even actions.
