### ISSUE TITLE
[BUG]: Hubspot - "Contact owner" dropdown fails to populate when adding a contact

### ISSUE THREAD

**Issue by GFoley83** [activepieces/activepieces#3445]
**Describe the bug**
Title

**To Reproduce**
Add a new Hubspot piece. 
Choose add a new contact
From the "Properties" multi-select choose "Contact owner"
Clicking the "Contact owner" drop down does nothing

**Expected behavior**
I should see a list of Hubspot team members to select from

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/838788/962fa197-34cf-4c06-9787-11cba85a5af7)

**Additional context**
If you toggle the "Dynamic value" option on the "Contact owner" field, you get the following error in the console:

![image](https://github.com/activepieces/activepieces/assets/838788/225e1c4e-e9be-47fa-ac6b-9868afe5a82f)

You can work around the bug by clicking the "Dynamic value" icon for "Contact owner" and hard-coding the contact ID.

**Comment by abuaboud** [comment]
Fixed by @kishanprmr , please reconnect your account.

**Comment by kishanprmr** [comment]
@abuaboud , reopening this issue because after updating the scope for the Oauth app, authorization is throwing an error saying "Insufficient scopes were provided. Please contact the app developer."

![image](https://github.com/activepieces/activepieces/assets/135701940/e1b3e2c7-6134-4797-a8eb-10715f9397f0)
