### ISSUE TITLE
[BUG]: Error when trying to save custom-auth app connections

### ISSUE THREAD

**Issue by fardeenpanjwani-codeglo** [activepieces/activepieces#3467]
**Describe the bug**
When creating app-connections for pieces that use CustomAuth, I get the following message: "Internal Connection error, failed please check your console." ( for Jira Cloud ) and "Internal Connection error, undefined" ( for Wordpress ).

**To Reproduce**
1. Create a new flow
2. Add the Jira Cloud piece
3. Select an action, and then create a connection
4. Fill in all the required details in the new-connection dialog box
5. Hit "Save"

**Expected behavior**
The application should save the app-connection and not throw an error

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/141914308/4590b9c8-2b6b-47b8-9deb-baf5fe42ac8e)

**Additional context**
- I've only tested Jira Cloud and Wordpress. Will test other pieces that use custom-auth.

**Comment by abuaboud** [comment]
The error because there is no try catch over validateAuth which make engine failure for example if you input jira instance url without https, It will throw an error and engine failure, instead of saying it failed to run validate auth.

This can be solved by moving description to be under field instead of tooltip, add proper handling for fields and last we should catch the error and display the correct error.
