### ISSUE TITLE
[BUG]: Storage piece fails when trying to use the "Add to list" action.

### ISSUE THREAD

**Issue by wise-introvert** [activepieces/activepieces#3759]
**Describe the bug**
Inserting an array into the storage and then trying to add to it using the storage piece doesn't work. Get "Key array-data is not an array" error.

**To Reproduce**

![storage-bug](https://github.com/activepieces/activepieces/assets/66718300/2f8613d5-8fdc-4382-b14a-0b1ff3d499af)

**Comment by abuaboud** [comment]
Interesting problem, but I think this is the wrong fix. It's a design flaw that everything entered in the put command is a string by default. We shouldn't try to parse any string to JSON, but since you are doing it for this action, it might be okay.

In your steps to reproduce, if you add {{ [] }} instead of [], it will be treated as an empty array since it's JavaScript and it resolves everything inside as JavaScript for original type.  or if you pass an array from the previous step that's an array it will work as well.

Let me get other team member suggestions here

@khaledmashaly @kishanprmr

**Comment by wise-introvert** [comment]
> Interesting problem, but I think this is the wrong fix. It's a design flaw that everything entered in the frontend directly is a string by default. We shouldn't try to parse any string to JSON, but since you are doing it for this action, it might be okay.
> 
> 
> 
> In your steps to reproduce, if you add {{ [] }} instead of [], it will be treated as an empty array since it's JavaScript and it resolves everything inside as JavaScript for original type.  or if you pass an array from the previous step that's an array it will work as well.
> 
> 
> 
> Let me get other team member suggestions here
> 
> 
> 
> @khaledmashaly @kishanprmr 

Yeah, you're right. This is more of a hotfix 😅.

**Comment by abuaboud** [comment]
@wise-introvert yes
