### ISSUE TITLE
[Question]: adding custom environment variables (.env) in ui and pieces packages

### ISSUE THREAD

**Issue by coglmn** [activepieces/activepieces#3846]
**Describe the bug**
Currently adding custom environment variables in the UI package seems not to work, with the error complaining 'process' is not defined

For example, in the UI's environment.ts (or environment.prod.ts) we want to get apiURL or a custom environment variable like below from the enviromment with proces.env:

customURL = process.env.AP_Custom_URL

Here, it complains that 'process' is undefined.

**To Reproduce**

Make the above change in the environment.ts in packages/ui/common/src/lib/environments/environment.ts and run dev.

**Expected behavior**
Environment variables to be available in UI and pieces packages.

**Screenshots**
NA

**Additional context**
Thank you for your help on pointing to the right documentation or configuration steps.

**Comment by abuaboud** [comment]
Hi @coglmn,

You can't directly use `process.env` because it is typically associated with server-side environments in Node.js and not for frontend projects (JavaScript compiler). However, for frontend, you can use the flags module and expose it from the flag service. Check this link: [https://github.com/activepieces/activepieces/blob/3d4a76f00a75462a87c5be5e4040a84501bbfde2/packages/ui/common/src/lib/service/flag.service.ts#L13](https://github.com/activepieces/activepieces/blob/3d4a76f00a75462a87c5be5e4040a84501bbfde2/packages/ui/common/src/lib/service/flag.service.ts#L13)

But keep in mind that flags are public endpoint, What is your use case?

**Comment by coglmn** [comment]
Thank you @abuaboud.! 

The goal was to pass URLs for some pieces and UI paths without hard cording them in environment.ts. What you highlighted about the flag service is good to know for passing non-secret info, as well. 

I have another question for you on the **AP_POSTGRES_SSL_CA** environment variable:   In case the Postgres database connection requires certificates, where those should be placed after setting this var to 'true'?
