### ISSUE TITLE
[BUG]: cannot add npm published piece

### ISSUE THREAD

**Issue by mariomeyer** [activepieces/activepieces#3847]
**Describe the bug**
When trying to add `piece-odoo` @ `0.0.2` version from NPM it fails

**To Reproduce**
1. Go to my pieces from the project.
2. Click on add Piece
3. Add the above piece.

**Expected behavior**
It should add the piece but now it fails

**Comment by abuaboud** [comment]
Can you please republish the package using the documented command, I took look at the npm and found from code tab, It's the source code instead of compiled version of piece which consists of type & js files.


https://www.npmjs.com/package/piece-odoo

I am closing this pr, please reopen If you have any other questions.
