### ISSUE TITLE
Better docs on data mapping

### ISSUE THREAD

**Issue by bachi76** [activepieces/activepieces#3876]
Path: /flows/passing-data

I think we need much better explanations and examples of data mapping. A very common task is to get a  list of objects, and now we want to map to a new list, but with only some objects.

From the docs I have no idea how that exactly works. Also there is an advanced data mapper, but with even less information.

**Comment by abuaboud** [comment]
Hi @bachi76,

A data mapper is typically used for renaming certain fields, but in your case, I believe you are looking for filtering rather than a data mapper. 

Unfortunately, we don't have a specific piece to filter a list of objects based on criteria. I recommend asking AI in the code snippet category; it works really well for such use cases.

I don't have any idea how to have generic filter piece, If you have suggestions let me know.

**Comment by ccollie** [comment]
I'd suggest using something like [Jsonata](jsonata.org) as the basis of this.

**Comment by abuaboud** [comment]
Hi @ccollie and @dangnhdev,

Great suggestion! You can contribute it as an action inside the data mapper. We would love to see such a contribution.

Please check https://www.activepieces.com/docs/developers/overview if someone will contribute.

**Comment by ccollie** [comment]
As some additional context, I got the idea for this from node-red, specifically the [Change Node](https://flowfuse.com/node-red/core-nodes/change/#:~:text=The%20Change%20node%20in%20Node%2DRED%20is%20used%20for%20modifying,for%20data%20transformation%20and%20manipulation)
For an idea of what's possible with Jsonata, see https://www.youtube.com/watch?v=uj4IQXOSRl8

I'm bandwidth limited currently but I will be using ActivePieces shortly in a production project, so I'm interested in seeing this happen.

**Comment by ccollie** [comment]
Working on this.

**Comment by abuaboud** [comment]
I am closing this, please open pull request If it's got done.
