### ISSUE TITLE
[BUG]: Unable to log in after registering an account with the correct credentials

### ISSUE THREAD

**Issue by bimsina** [activepieces/activepieces#4413]
**Describe the bug**

Unable to log in after registering an account with the correct credentials. The system returns the following error message:

```json
{
    "code":"INVALID_CREDENTIALS",
    "params":null
}
```

**To Reproduce**

1. Clone the repository.
2. Execute `sh tools/deploy.sh` to generate a .env file.
3. Use the command `docker compose -p activepieces up` to start the services.
4. Register a new account successfully.
5. Log out from the newly created account.
6. Register another account using a different email address.
7. Log out again.
8. Attempt to log in with the credentials of the second account results in the error mentioned above.

**Expected behavior**

The expectation is that the account should log in successfully when the correct credentials are provided.

**Additional context**

From my initial analysis, it appears that a new `platformId` is generated for each registration. During the login process, the system seems to fail in locating the corresponding platformId, resulting in an "user not found" scenario. This might be the root cause of the login issues encountered.

**Comment by abuaboud** [comment]
Hi @bimsina 

Good catch, let me try to take look at that

**Comment by abuaboud** [comment]
@allcontributors please add @bimsina for bug

**Comment by bimsina** [comment]
@abuaboud Any updates on this issue?

**Comment by abuaboud** [comment]
Yes, I am waiting for this to land: https://github.com/activepieces/activepieces/pull/4481, to start progressing on the issue.

Now, the issue here is that we need the platform ID to authenticate the user. Usually, we retrieve it from the custom domain, or in the community edition, we simply get the oldest platform.

When the user logs in, the email is only unique across platforms at the moment, which means we can't determine which platform the user belongs to. However, I think in the community edition, we can make the email unique across instance, and that's way we can reverse-map to the platform ID.

I am hoping to finish all work related to this change as soon as possible so we can land it.

**Comment by abuaboud** [comment]
I am closing this issue, It will be fixed in the next release (after 0.25.1) It's already merged in main.

https://github.com/activepieces/activepieces/pull/4563
