### ISSUE TITLE
[BUG]: Request for Support with Account Issue - All Flows (200) Stuck in RUNS State 

### ISSUE THREAD

**Issue by ivansileo** [activepieces/activepieces#5687]
Hi everyone,

I’m experiencing a critical issue **(5 days)** with my account on Activepieces and urgently need to reach out to the support team for assistance. Despite numerous attempts to post both here and on Discord over the past three days, I’ve received no response.

All my flows triggered within this period automatically end up stuck in the “RUNS” section. As shown in the attached screenshots, every step within these flows is indefinitely spinning without starting or completing. this issue has led to approximately 200 of my flows getting stuck in “RUNS.”

These flows have consistently worked in the past without issues, and no recent
changes have been made to their configurations, leading me to believe this is an account-specific problem. Unfortunately, I’m also unable to find an option to stop or cancel these flows, exacerbating the situation.

Could anyone advise on how to directly contact the Activepieces support team or suggest any potential solutions to unblock these flows?
My account is : **sileo.ivan@gmail.com**

Thank you in advance for any help you can provide!

**Screenshots**
![1](https://github.com/user-attachments/assets/8cd54e93-5b05-4661-bb99-91380e3d53d8)
![2](https://github.com/user-attachments/assets/8e7846cc-ed0f-42a8-8019-2aeb40ace2e5)
![3](https://github.com/user-attachments/assets/80046e6e-958a-4115-84b4-e4f50b477697)

**Comment by abuaboud** [comment]
https://community.activepieces.com/t/not-able-to-stop-100-flows-running/6379/14?u=abuaboud

Finally we found the root cause, It was in gmail step, It was returning huge error message which caused the engine to fail to save the logs.

Now they are all saved, and runs that were pending now complete, although the engine now replace the huge error message with (truncate) to make it fit within the log size limit.
