### ISSUE TITLE
Mattermost

### ISSUE THREAD

**Issue by tcurdt** [activepieces/activepieces#727]
**Describe your usecase.**

I want to send messages to a Mattermost channel from a Mattermost bot account

https://api.mattermost.com/

**Describe alternatives you've considered**

I guess with one could call out to a shell and run a binary.
But I don't really see that as an alternative.

**Comment by abuaboud** [comment]
Thank you for raising the issue!  I have moved it to the pieces board.

We have been receiving numerous requests lately, but we are working hard to create as many pieces as possible. 🙌 Hopefully, contributors can also pick this up and join in on the fun! 

Let's keep the pieces flowing! 🌟

**Comment by kanarelo** [comment]
OpenAPI Specification: blob:https://api.mattermost.com/6e5080e4-234f-445b-be9a-aa177c5959c1

**Comment by abuaboud** [comment]
Hello, @tcurdt. I am currently working on this and wanted to ask if it would be sensible to use incoming webhooks for sending messages. In my opinion, creating incoming webhooks would be easier for the end user compared to OAuth2 app.

![image](https://user-images.githubusercontent.com/1812998/227716191-c2410623-418c-44b1-9b35-c6cc44dd5fb7.png)

What do you think?

**Comment by tcurdt** [comment]
I am not sure I follow.

As a user I would expect to create a bot account. Nothing more.
That bot account should have a token for auth from activepieces.
So no OAuth2 - but manually creating webhooks also feels off.

Not sure if you can/want to have a look from a license point of view - but I think that's how n8n has implemented it

https://github.com/n8n-io/n8n/tree/dd20127961bb403f2bd1be2e3729aecda58c225d/packages/nodes-base/nodes/Mattermost

**Comment by abuaboud** [comment]
@tcurdt, I apologize for my previous message. Let me clarify my explanation.

Mattermost has a feature called "Incoming Webhook". It creates a unique URL that you can use to send messages. You can access this feature by going to "Integrations" in same place where you can create bot account.

The reason I suggest this approach instead of creating bot accounts is that bot accounts cannot list channels to my knowledge. 

This means that users need to find the channel ID manually. However, with the "Incoming Webhook" feature, you can easily select the channel from the interface.

Check the screenshot below:
![image](https://user-images.githubusercontent.com/1812998/227747315-92e1eadb-b090-4921-aa2e-6574fda03c0f.png)

What do you think now?

**Comment by tcurdt** [comment]
Using webhooks feels like a work around.
I rather see the messages inside mattermost coming from the dedicated bot account.

Personally I wouldn't mind looking up the id manually.
But it seems like entering the chat name should also work:

  https://github.com/mattermost/mattermost-bot-sample-golang/blob/master/bot_sample.go

Maybe the "List" operation is only temporarily broken?
It sounds like they have just changed the data structure.

Thanks for working on this!

**Comment by abuaboud** [comment]
@tcurdt Great, I should modify it to utilize a bot account instead. Additionally, I will create documentation detailing how to retrieve the channel ID.

**Comment by raqibnur** [comment]
The bot account no longer works; I believe OAuth2 is the best solution. I used OAuth2 with Zapier and everything worked fine.
