### ISSUE TITLE
Create Actions from Swagger/OpenAPI JSON

### ISSUE THREAD

**Issue by kanarelo** [activepieces/activepieces#748]
**Is your feature request related to a problem? Please describe.**
We need a way to create actions by uploading/providing a swagger JSON 

**Describe the solution you'd like**
Maybe during the creation of a piece, the user can provide a swagger JSON, then select from a multi list of crud/process endpoints that they may want to create actions from.

**Additional context**
- Support may be for actions at the moment, if webhooks are in the JSON, #746 may benefit from this

**Comment by abuaboud** [comment]
In my opinion, while OpenAPI is a useful tool, there are certain fields that cannot be easily auto-generated and made no-code friendly. One such example is a dynamic dropdown where the options for the user are fetched and presented as a dropdown, allowing them to select from the list rather than filling in an ID directly.

Going to close it for now, feel free to reopen.
