### ISSUE TITLE
Configs deleted?

### ISSUE THREAD

**Issue by astorozhevsky** [activepieces/activepieces#862]
@abuaboud I wanted to reach out regarding the recent update to the library. I noticed that the 'Configs' feature [has been removed](https://github.com/activepieces/activepieces/commit/25eeea8999d5e1e7baee06ed9169973ff3e986dd) in the new version. I was wondering if you could provide some insight into why this decision was made?

Additionally, as someone who relied heavily on the 'Configs' feature, I am curious if there is an alternative solution or recommended workaround that I can use to achieve similar functionality in the new version of the library.

Thank you!

**Comment by abuaboud** [comment]
@astorozhevsky I would like to begin by apologizing for not communicating this. I also want to thank you for bringing up this issue.

The reason we removed the feature was that it was difficult to maintain. We used to version collections because of the configurations, and this made it hard to keep two moving objects (flow versions and collection versions) in sync. This will cause issues when implementing features like exporting and importing flow features. The code was initially developed for a legacy product, and that part was moved along with it.

In this commit we removed the configs and the collection version entity as well.

However, we are want to bring back this feature in a different form. We have some suggestions, such as creating an interface to view/delete from the collection store (same store used in store piece) or using project-level variables.

As of now, the current workaround is to add a code piece, put all the configurations in it, and let say the name of code piece is "step_1." Then, you can use it any place where you want to use the configuration in same flow.


![image](https://user-images.githubusercontent.com/1812998/227261623-15c71638-f9f2-4322-a0a3-debbe6448a1e.png)

Please let me know if this solves the issue for you, or if you have another suggestions how this feature should be re-implemented.
