### ISSUE TITLE
[BUG]: Logs

### ISSUE THREAD

**Issue by raghav39** [activepieces/activepieces#910]
**Describe the bug**
Standard logger is probably not used

**Expected behavior**
- Not able to set log levels - debug, info, error etc
- All the logs seems like console logs which are spread across multiple lines in the cloud logging enviornment. Filtering logs and batching becomes difficult

**Screenshots**
<img width="409" alt="Screenshot 2023-03-28 at 7 45 26 PM" src="https://user-images.githubusercontent.com/11975721/228267240-37a17da9-571b-44ef-8365-112c79fce83c.png">

**Comment by abuaboud** [comment]
I believe this is because we're using pino-pretty to format the logs, and the default format is JSON.

It should be removed `pino-pretty` when in production mode.

Link to the relevant code: https://github.com/activepieces/activepieces/blob/main/packages/backend/src/app/helper/logger.ts

I will mark this as good first issue.
