### ISSUE TITLE
[BUG]: Slack permission

### ISSUE THREAD

**Issue by raghav39** [activepieces/activepieces#913]
**Describe the bug**
Is it possible to avoid the slack bot permission to read the messages from all public channels even if the bot is not part of?

**Screenshots**
<img width="701" alt="Screenshot 2023-03-28 at 7 59 42 PM" src="https://user-images.githubusercontent.com/11975721/228272022-0f23d221-34eb-49b2-9a0a-286d98d61eab.png">

**Comment by abuaboud** [comment]
Currently, both the frontend request all app permissions might be required. 

Even though channels:history required for the new message trigger. Allowing the user to choose the permissions may lead to a bad user experience, as mentioned in this related issue: https://github.com/activepieces/activepieces/issues/803.

Instead, for this use case, I suggest creating your own OAuth2 application on Slack, luckily which is a easy process for slack. and use your own app credentials instead of activepieces.

**Comment by raghav39** [comment]
Yep, that would work. Thanks :)
