### ISSUE TITLE
Find piece

### ISSUE THREAD

**Issue by Arffeh** [activepieces/activepieces#967]
**Describe your usecase.**
Find from input, return found thing as output using Regex (or just passthrough all text and use it as logic/decisionmaking)

Optional flag, abort if text found, or abort if text not found

**Comment by abuaboud** [comment]
Can you mention the usecases for this piece?

**Comment by Arffeh** [comment]
Work order comes in from a specific place, use regex to locate something specific for the next flow, or abort if not found

**Comment by abuaboud** [comment]
I believe it would be more suitable to implement this functionality as functions instead of steps, considering that inline functions (custom JavaScript) are permitted. Therefore, I suggest exploring the option of utilizing functions rather than steps. You can find the related discussion on GitHub at: [GitHub Issue 1018](https://github.com/activepieces/activepieces/issues/1018).


Feel free to reopen :D
