### ISSUE TITLE
Add support for teams in same project in ActivePieces

### ISSUE THREAD

**Issue by charanjit-singh** [activepieces/activepieces#971]
**Is your feature request related to a problem? Please describe.**

ActivePieces currently does not support multiple users, which is inconvenient for teams or groups who need to collaborate on projects. This creates a problem for users who need to share access and collaborate on projects with other users.

**Describe the solution you'd like**
Implement a workspace feature in ActivePieces, similar to the one used in Pipedream. This would include the ability to invite users, give and revoke access, and collaborate on projects together. By implementing this feature, users would be able to work together on projects without having to share login credentials or work on a single account. This would increase collaboration and productivity, as well as make it easier for teams to manage their projects.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by abuaboud** [comment]
I am linking another related issue here: https://github.com/activepieces/activepieces/issues/869

This feature currently on roadmap but It will be in commercial edition, Do you have requirements / suggestions on  when there is two users are working on the flow time at same time.

The ideal scenario would be to allow live collaboration, but I can't see huge benefit compared to the effort needed since people should spend little time working on the flows and the rest will be background.

What do you think?

**Comment by charanjit-singh** [comment]
https://github.com/yjs/yjs can be utilized

**Comment by charanjit-singh** [comment]
We can postpone implementation of real time editing (but if someone is already editing, a message showing that changes may not be saved, just like wordpress, can be used till that time)

Also what are the terms for Enterprise licensing?

**Comment by abuaboud** [comment]
@charanjit-singh We never though of the pricing for whitelabel the product inside the website, I will ping you on discord and discuss the options and let's brain storm together.

**Comment by abuaboud** [comment]
Merged First Version on the cloud
